name: emacs-ffi

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false

    steps:
      
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        sudo apt-get update && sudo apt-get install -y emacs libltdl7 libltdl-dev libffi-dev libgsl-dev       
        make
        make check

    - name: Run gsl test
      run: |
        emacs -batch --eval '(message "hello")'
        cd examples/gsl && make && pwd && ls && ldd gsl-linalg.so && make test
