# adapted from https://github.com/purcell/package-lint/blob/master/.github/workflows/test.yml
name: emacs-ffi

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.4

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

      
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        sudo apt-get update && sudo apt-get install -y libltdl7 libltdl-dev libffi-dev libgsl-dev
        make
        ls *
        # make check

    - name: Run gsl test
      run: |
        find /usr/lib -name "libgsl.so.27"
        pkg-config --cflags gsl
        pkg-config --libs gsl
        cd examples/gsl && make && pwd && ls && make test
